FIND_PATH(
	ZLIB_INCLUDE_DIR
	NAMES zlib.h zconf.h
	PATHS /usr/local/include/
)

FIND_PATH(
	ZLIB_BINARY_DIRS
	NAMES zlib.lib zlibd.lib zlibstatic.lib zlibstaticd.lib 
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	ZLIB_LIBRARY
	NAMES zlib
	PATHS /usr/local/lib/
)

IF (ZLIB_INCLUDE_DIR AND ZLIB_LIBRARY AND ZLIB_BINARY_DIRS)
    SET(ZLIB_FOUND TRUE)
ENDIF (ZLIB_INCLUDE_DIR AND ZLIB_LIBRARY AND ZLIB_BINARY_DIRS)

IF (ZLIB_FOUND)
    IF (NOT ZLIB_FIND_QUIETLY)
        MESSAGE(STATUS "Found library: ${ZLIB_LIBRARY}")
    ENDIF (NOT ZLIB_FIND_QUIETLY)
ELSE (ZLIB_FOUND)
    IF (ZLIB_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "library")
    ENDIF (ZLIB_FIND_REQUIRED)
ENDIF (ZLIB_FOUND)
